### ISSUE TITLE
Long runtime when running post-acquisition annotation

### ISSUE THREAD

**Issue by pablovgd** [phenomecentre/peakPantheR#33]
Dear all,

I've been exploring peakPantheR as an option for automated targeted metabolomics processing on data from UHPLC-HRMS (Thermo Orbitrap: Q-exactive & Exploris 120 instrumentation).
However, runtimes seem exaggeratedly long for the amount of samples I'm performing tests on. 
Currently, I'm testing it on 3 QC samples, saved in .mzML format (centroided, negative ionisation, converted and filtered with Proteowizard's msConvert) in combination with a targeted feature list of 137 compounds.
I've tried running from within the GUI and directly from command line.
Runtimes exceed 12h+ without having finished. Maybe something is going wrong under the hood? 
Files to reproduce my tests can be downloaded here: https://filesender.belnet.be/?s=download&token=56450931-4adb-4ce1-8c45-0cf4f745c9ee

Thanks in advance for the help.

Kind regards,
Pablo

**Comment by Gscorreia89** [comment]
Hi, 

Thank you for your interest in peakPantheR. I have ran your example files and managed to replicate the error. 
The error is caused by an incorrect stopping condition in the search for the data acquisition timestamp in the mzML file. We will isssue a patch for this soon. 

However, the mzML file should have a startTimeStamp timestamp with the acquisition files, and I couldn't find any on your examples, which is weird. Can you please confirm how the files were converted to .mzML? Was there any intermediate conversion to .mzXML? I see some weird tags mentioning a .mzXML file in the .xml info.

**Comment by pablovgd** [comment]
Hi @Gscorreia89,

Thanks for the quick reply!
That is really weird indeed, but it indeed might have been the case that those files were once intermediately converted to mzXML and then to mzML.
Files were converted using msconvert by proteowizard, centroided and subsetted per polarity.
In any case, I tried converting some raw files straight to mzML and now I get the following error messages:
```
3 file(s) failed to process:
                file                                                                            error
1 211201s009neg.mzML Check input not all datapoints for window #1 are into the corresponding ROI (rt)
2 211201s010neg.mzML                                            missing value where TRUE/FALSE needed
3 211201s011neg.mzML                                            missing value where TRUE/FALSE needed
No file left in the object!
Annotation object reordered by sample acquisition date
```
Link to newly converted .mzML's: https://filesender.belnet.be/?s=download&token=dc236b72-078a-40b9-a69e-90e8f6222f1e

Thanks again for taking a look at this!

Kind regards,
Pablo

**Comment by Gscorreia89** [comment]
Hi,

I have ran your new files and all seems to work (both in parallel and serial) - just to confirm, see below the code I have used and let me know if you have any issues running it on these files:

`library(peakPantheR)

input_spectraPaths <- list.files('./', pattern='mzML', full.names=T)

input_targetFeatTable <- read.csv('./1-fitParams_example_UI.csv')

\# The cpdID is expected to be string, and not numerical
input_targetFeatTable$cpdID <- as.character(input_targetFeatTable$cpdID)

init_annotation <- peakPantheRAnnotation(spectraPaths = input_spectraPaths,
                        targetFeatTable = input_targetFeatTable)

annotation_result <- peakPantheR_parallelAnnotation(init_annotation, ncores=3, curveModel='skewedGaussian', verbose=TRUE)

outputAnnotationDiagnostic(annotation_result$annotation, saveFolder='./', 
                            savePlots=TRUE, 
                            verbose=TRUE, ncores=3)
`

**Comment by pablovgd** [comment]
Thanks again for trying the files!
I don't know exactly why this is happening, but currently it seems to work fine if I first output the target table as .csv and then read it back into R, whilst using the table directly results in errors (column data types are exactly the same). 
Anyhow, I'll see if I can solve this weird behaviour, but for now, peakpanther itself seems to work fine.
Thanks for helping out!

**Comment by Gscorreia89** [comment]
Hi,

On my example script I added  the following line to convert the cpdID to character - maybe its because of that? 
`input_targetFeatTable$cpdID <- as.character(input_targetFeatTable$cpdID)
`
Glad to know if its working. We have added a patch to ensure situations like this (mzML without the expected timestamp) still work and there is a specific warning out, but it won't be out until the next BioC release.
